Model:
  __class_name__: LDMModule
  __init_params__:
    denoiser:
      __class_name__: DiT
      __init_params__:
        hidden_dim: 768
        num_heads: 12
        input_dim: 8
        learn_sigma: true
    diffusion_configs:
      timestep_respacing: ""
    vae:
      __class_name__: VAEModule
      __init_params__:
        encoder:
          __class_name__: TransformerEncoder
          __init_params__:
            d_model: 512
            num_layers: 8
        decoder:
          __class_name__: TransformerDecoder
          __init_params__:
            d_model: 512
            num_layers: 8
        latent_dim: 8
        loss_weights: {}

Sample:
  data:
    dataset:
      __class_name__: NumAtomsCrystalDataset
      __init_params__:
        total_num: 10
    sampler:
      __class_name__: BatchSampler
      __init_params__:
        batch_size: 10
  build_structure_cfg:
    format: array
    niggli: false
  metrics:
    __class_name__: StructGenMetric
    __init_params__:
      reference_file_path: "./data/mp_20/novelty_reference.pkl"
