Model:
  __class_name__: LDMModule
  __init_params__:
    normalize_latent: true
    vae_ckpt_path: test-for-weight/converted_weights/vae_paddle.pdparams
    denoiser:
      __class_name__: DiT
      __init_params__:
        hidden_dim: 768
        num_layers: 12
        num_heads: 12
        mlp_ratio: 4.0
        input_dim: 8
        learn_sigma: true
    diffusion_configs:
      timestep_respacing: ""
      noise_schedule: linear
      use_kl: false
      sigma_small: false
      predict_xstart: false
      learn_sigma: true
      rescale_learned_sigmas: false
      diffusion_steps: 1000
    vae:
      __class_name__: VAEModule
      __init_params__:
        encoder:
          __class_name__: TransformerEncoder
          __init_params__:
            max_num_elements: 100
            d_model: 512
            nhead: 8
            dim_feedforward: 2048
            activation: gelu
            dropout: 0.0
            num_layers: 8
        decoder:
          __class_name__: TransformerDecoder
          __init_params__:
            max_num_elements: 100
            d_model: 512
            nhead: 8
            dim_feedforward: 2048
            activation: gelu
            dropout: 0.0
            num_layers: 8
        latent_dim: 8
        loss_weights: {}

Sample:
  data:
    dataset:
      __class_name__: MP20Dataset
      __init_params__:
        path: "./data/mp_20/test.csv"
        build_structure_cfg:
          format: cif_str
          num_cpus: 10
    sampler:
      __class_name__: BatchSampler
      __init_params__:
        shuffle: false
        drop_last: false
        batch_size: 10
  build_structure_cfg:
    format: array
    niggli: false
  post_transforms: null
  metrics: null
